name: Publish wiki
on:
  push:
    branches: [main]
    paths:
      - wiki/**
      - .github/workflows/publish-wiki.yml
concurrency:
  group: publish-wiki
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Publish to MoonDeck wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        token: ${{ secrets.PUBLISH_TOKEN }}
        repository: FrogTheFrog/moondeck
        dry-run: true

      - name: Publish to MoonDeckBuddy wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        token: ${{ secrets.PUBLISH_TOKEN }}
        repository: FrogTheFrog/moondeck-buddy
        dry-run: true